/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/simple-login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/category`; params?: Router.UnknownInputParams; } | { pathname: `/components/filter`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/SimpleMapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AdminAssignmentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MeetingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/simple-login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/category`; params?: Router.UnknownOutputParams; } | { pathname: `/components/filter`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SimpleMapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AdminAssignmentScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MapsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MeetingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/simple-login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/category${`?${string}` | `#${string}` | ''}` | `/components/filter${`?${string}` | `#${string}` | ''}` | `/components/MapComponent${`?${string}` | `#${string}` | ''}` | `/components/SimpleMapComponent${`?${string}` | `#${string}` | ''}` | `/screens/AdminAssignmentScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/MapsScreen${`?${string}` | `#${string}` | ''}` | `/screens/MeetingsScreen${`?${string}` | `#${string}` | ''}` | `/screens/ProfileScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/simple-login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/category`; params?: Router.UnknownInputParams; } | { pathname: `/components/filter`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/SimpleMapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AdminAssignmentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MeetingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProfileScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
